const news = {

    data: [
      {
        "article_id": "ba50620030053433181b318782570d17",
        "title": "Gold prices set fresh record",
        "link": "https://www.bangkokpost.com/business/general/2864478/gold-prices-set-fresh-record",
        "keywords": null,
        "creator": null,
        "video_url": null,
        "description": "NEW YORK - Gold prices rose more than 1% to reach a record high on Thursday, helped by expectations of an interest rate cut by the Federal Reserve next week after US data signalled a slowing of the economy.",
        "content": "ONLY AVAILABLE IN PAID PLANS",
        "pubDate": "2024-09-12 14:35:00",
        "pubDateTZ": "UTC",
        "image_url": "https://static.bangkokpost.com/media/content/20240912/c1_2864478.jpg",
        "source_id": "bangkokpost",
        "source_priority": 42430,
        "source_name": "Bangkok Post",
        "source_url": "http://BangkokPost.com",
        "source_icon": "https://i.bytvi.com/domain_icons/bangkokpost.png",
        "language": "english",
        "country": [
          "thailand"
        ],
        "category": [
          "business"
        ],
        "ai_tag": "ONLY AVAILABLE IN PROFESSIONAL AND CORPORATE PLANS",
        "sentiment": "ONLY AVAILABLE IN PROFESSIONAL AND CORPORATE PLANS",
        "sentiment_stats": "ONLY AVAILABLE IN PROFESSIONAL AND CORPORATE PLANS",
        "ai_region": "ONLY AVAILABLE IN CORPORATE PLANS",
        "ai_org": "ONLY AVAILABLE IN CORPORATE PLANS",
        "duplicate": false
      },
      {
        "article_id": "90920348a526b1a622cbba4c7164c9c3",
        "title": "นายกฯอิ๊งค์กลับแล้ว หลังอยู่แถลงนโยบายทั้งวัน ยอมรับหมดแรง เจอกันเชียงรายพรุ่งนี้",
        "link": "https://www.matichon.co.th/politics/news_4787896",
        "keywords": [
          "นิวส์มอนิเตอร์",
          "ภาพนำ",
          "แพทองธาร ชินวัตร",
          "การเมือง"
        ],
        "creator": [
          "kk"
        ],
        "video_url": null,
        "description": "นายกฯ เดินทางออกจากอาคารรัฐสภา หลังใช้เวลาตลอดทั้งวันแถ [...]",
        "content": "ONLY AVAILABLE IN PAID PLANS",
        "pubDate": "2024-09-12 14:32:17",
        "pubDateTZ": "UTC",
        "image_url": "https://www.matichon.co.th/wp-content/uploads/2024/09/nayok1.jpg",
        "source_id": "matichon",
        "source_priority": 523464,
        "source_name": "มติชนออนไลน์\"",
        "source_url": "https://www.matichon.co.th",
        "source_icon": "https://i.bytvi.com/domain_icons/matichon.jpg",
        "language": "thai",
        "country": [
          "thailand"
        ],
        "category": [
          "politics"
        ],
        "ai_tag": "ONLY AVAILABLE IN PROFESSIONAL AND CORPORATE PLANS",
        "sentiment": "ONLY AVAILABLE IN PROFESSIONAL AND CORPORATE PLANS",
        "sentiment_stats": "ONLY AVAILABLE IN PROFESSIONAL AND CORPORATE PLANS",
        "ai_region": "ONLY AVAILABLE IN CORPORATE PLANS",
        "ai_org": "ONLY AVAILABLE IN CORPORATE PLANS",
        "duplicate": false
      },
      {
        "article_id": "664ae2d4cf6e97ec1861f2244b67ee29",
        "title": "เปิดตัวจัดเต็มศิลปิน รับลมชมทะเลริมหาดชะอํา คัลเลอร์ฟูลด้วยสีสันเต็มอิ่มตลอด",
        "link": "https://www.thairath.co.th/entertain/news/2814093",
        "keywords": null,
        "creator": null,
        "video_url": null,
        "description": "เปิดตัวขบวนศิลปินชั้นนํามากมายที่คัดสรรมามอบความสุขให้แฟนๆได้สนุก และดื่มด่ําในบรรยากาศริมทะเลไปกับ เทศกาลดนตรี",
        "content": "ONLY AVAILABLE IN PAID PLANS",
        "pubDate": "2024-09-12 14:31:02",
        "pubDateTZ": "UTC",
        "image_url": "https://static.thairath.co.th/media/Kg2lj2gY7z4zNnRd7SuBqnBQIHxt0vKHUuH.jpg",
        "source_id": "thairath",
        "source_priority": 44507,
        "source_name": "Thairath",
        "source_url": "https://www.thairath.co.th",
        "source_icon": "https://i.bytvi.com/domain_icons/thairath.png",
        "language": "thai",
        "country": [
          "thailand"
        ],
        "category": [
          "entertainment"
        ],
        "ai_tag": "ONLY AVAILABLE IN PROFESSIONAL AND CORPORATE PLANS",
        "sentiment": "ONLY AVAILABLE IN PROFESSIONAL AND CORPORATE PLANS",
        "sentiment_stats": "ONLY AVAILABLE IN PROFESSIONAL AND CORPORATE PLANS",
        "ai_region": "ONLY AVAILABLE IN CORPORATE PLANS",
        "ai_org": "ONLY AVAILABLE IN CORPORATE PLANS",
        "duplicate": false
      },
      {
        "article_id": "af09310a2416b12b1ee618e484acfa84",
        "title": "“แพทองธาร” ออกจากสภา รับวันนี้หมดแรง พรุ่งนี้ไปเชียงราย แฟนคลับมอบกุหลาบ-สวมกอด",
        "link": "https://www.thairath.co.th/news/politic/2814092",
        "keywords": null,
        "creator": null,
        "video_url": null,
        "description": "นายกฯ ออกจากห้องประชุมรัฐสภา หลังใช้เวลาตลอดทั้งวันแถลงนโยบายรัฐบาลและชี้แจง ขอไม่ให้สัมภาษณ์ บอกไปเจอกันที่เชียงราย ยอมรับวันนี้หมดแรง ด้านแฟนคลับมอบดอกกุหลาบให้กําลังใจ",
        "content": "ONLY AVAILABLE IN PAID PLANS",
        "pubDate": "2024-09-12 14:31:00",
        "pubDateTZ": "UTC",
        "image_url": "https://static.thairath.co.th/media/Kg2lj2gY7z4zNnRd7SuBqnBQap9QdefS0mR.jpg",
        "source_id": "thairath",
        "source_priority": 44507,
        "source_name": "Thairath",
        "source_url": "https://www.thairath.co.th",
        "source_icon": "https://i.bytvi.com/domain_icons/thairath.png",
        "language": "thai",
        "country": [
          "thailand"
        ],
        "category": [
          "top"
        ],
        "ai_tag": "ONLY AVAILABLE IN PROFESSIONAL AND CORPORATE PLANS",
        "sentiment": "ONLY AVAILABLE IN PROFESSIONAL AND CORPORATE PLANS",
        "sentiment_stats": "ONLY AVAILABLE IN PROFESSIONAL AND CORPORATE PLANS",
        "ai_region": "ONLY AVAILABLE IN CORPORATE PLANS",
        "ai_org": "ONLY AVAILABLE IN CORPORATE PLANS",
        "duplicate": false
      },
      {
        "article_id": "d98cea02e1792a55a9bc4c41f0ba4ff3",
        "title": "Central Europe braces for worst floods in decades",
        "link": "https://www.channelnewsasia.com/world/central-europe-braces-worst-floods-decades-cyclone-boris-4604311",
        "keywords": [
          "world"
        ],
        "creator": null,
        "video_url": null,
        "description": null,
        "content": "ONLY AVAILABLE IN PAID PLANS",
        "pubDate": "2024-09-12 14:31:00",
        "pubDateTZ": "UTC",
        "image_url": "https://onecms-res.cloudinary.com/image/upload/s--fE-cINEs--/c_fill,h_900,w_1600/f_auto,q_auto/v1/mediacorp/cna/image/2024/09/12/000_dv1500523.jpg?itok=5otLaMaj",
        "source_id": "channelnewsasia",
        "source_priority": 37829,
        "source_name": "Cna",
        "source_url": "https://www.channelnewsasia.com",
        "source_icon": "https://i.bytvi.com/domain_icons/channelnewsasia.jpg",
        "language": "english",
        "country": [
          "georgia",
          "yemen",
          "afghanistan",
          "cyprus",
          "india",
          "singapore",
          "saudi arabia",
          "maldives",
          "japan",
          "united arab emirates",
          "malaysia",
          "china",
          "south korea",
          "north korea",
          "taiwan",
          "thailand",
          "pakistan",
          "mongolia",
          "brunei",
          "lebanon",
          "indonesia",
          "kyrgyzstan",
          "syria",
          "israel",
          "bhutan",
          "iran",
          "turkey",
          "armenia",
          "qatar",
          "philippines",
          "hong kong",
          "kazakhstan",
          "iraq",
          "bangladesh",
          "laos",
          "vietnam",
          "timor-leste",
          "kuwait",
          "myanmar",
          "azerbaijan",
          "jordan",
          "nepal",
          "sri lanka",
          "uzbekistan",
          "turkmenistan",
          "macau",
          "bahrain",
          "cambodia",
          "tajikistan"
        ],
        "category": [
          "world"
        ],
        "ai_tag": "ONLY AVAILABLE IN PROFESSIONAL AND CORPORATE PLANS",
        "sentiment": "ONLY AVAILABLE IN PROFESSIONAL AND CORPORATE PLANS",
        "sentiment_stats": "ONLY AVAILABLE IN PROFESSIONAL AND CORPORATE PLANS",
        "ai_region": "ONLY AVAILABLE IN CORPORATE PLANS",
        "ai_org": "ONLY AVAILABLE IN CORPORATE PLANS",
        "duplicate": true
      },
      {
        "article_id": "4ea2af45fcfab98cf63f10d0d76e0f79",
        "title": "Save 70% Off a 1 Year Sam's Club Membership",
        "link": "https://sea.ign.com/deal/220499/save-70-off-a-1-year-sams-club-membership",
        "keywords": [
          "ign misc",
          "deal"
        ],
        "creator": [
          "Eric Song"
        ],
        "video_url": null,
        "description": "4 Times Less Expensive Than a Costco MembershipSam's Club is currently offering 70% off its 1-year general membership. The membership normally costs you $50, so right now you'd only be paying $15. The promotion is reserved for anyone who hasn't been a Sam's Club member for the past 6 months. Sam's Club is owned ...",
        "content": "ONLY AVAILABLE IN PAID PLANS",
        "pubDate": "2024-09-12 14:30:00",
        "pubDateTZ": "UTC",
        "image_url": "https://sm.ign.com/ign_ap/deal/s/save-70-of/save-70-off-a-1-year-sams-club-membership_w8z8.jpg",
        "source_id": "ign",
        "source_priority": 144,
        "source_name": "Ign Southeast Asia",
        "source_url": "https://sea.ign.com",
        "source_icon": "https://i.bytvi.com/domain_icons/ign.png",
        "language": "english",
        "country": [
          "vietnam",
          "singapore",
          "malaysia",
          "myanmar",
          "philippines",
          "thailand",
          "brunei",
          "indonesia",
          "cambodia"
        ],
        "category": [
          "top"
        ],
        "ai_tag": "ONLY AVAILABLE IN PROFESSIONAL AND CORPORATE PLANS",
        "sentiment": "ONLY AVAILABLE IN PROFESSIONAL AND CORPORATE PLANS",
        "sentiment_stats": "ONLY AVAILABLE IN PROFESSIONAL AND CORPORATE PLANS",
        "ai_region": "ONLY AVAILABLE IN CORPORATE PLANS",
        "ai_org": "ONLY AVAILABLE IN CORPORATE PLANS",
        "duplicate": false
      },
      {
        "article_id": "85df690ed7ca9acd3f257d1af085e015",
        "title": "Gaza economy shrinks to less than a sixth of its pre-war size, UN report says",
        "link": "https://www.channelnewsasia.com/world/gaza-economy-shrinks-less-sixth-its-pre-war-size-un-report-says-4604261",
        "keywords": [
          "world"
        ],
        "creator": null,
        "video_url": null,
        "description": null,
        "content": "ONLY AVAILABLE IN PAID PLANS",
        "pubDate": "2024-09-12 14:29:24",
        "pubDateTZ": "UTC",
        "image_url": "https://onecms-res.cloudinary.com/image/upload/s--xl4G8jp1--/c_fill,h_900,w_1600/fl_relative,g_south_east,l_mediacorp:cna:watermark:2024-04:reuters_1,w_0.1/f_auto,q_auto/v1/one-cms/core/2024-09-12t133247z_1_lynxmpek8b0kc_rtroptp_3_israel-palestinians-gaza-plastic-fuel.jpg?itok=UTe_1KjK",
        "source_id": "channelnewsasia",
        "source_priority": 37829,
        "source_name": "Cna",
        "source_url": "https://www.channelnewsasia.com",
        "source_icon": "https://i.bytvi.com/domain_icons/channelnewsasia.jpg",
        "language": "english",
        "country": [
          "georgia",
          "yemen",
          "afghanistan",
          "cyprus",
          "india",
          "singapore",
          "saudi arabia",
          "maldives",
          "japan",
          "united arab emirates",
          "malaysia",
          "china",
          "south korea",
          "north korea",
          "taiwan",
          "thailand",
          "pakistan",
          "mongolia",
          "brunei",
          "lebanon",
          "indonesia",
          "kyrgyzstan",
          "syria",
          "israel",
          "bhutan",
          "iran",
          "turkey",
          "armenia",
          "qatar",
          "philippines",
          "hong kong",
          "kazakhstan",
          "iraq",
          "bangladesh",
          "laos",
          "vietnam",
          "timor-leste",
          "kuwait",
          "myanmar",
          "azerbaijan",
          "jordan",
          "nepal",
          "sri lanka",
          "uzbekistan",
          "turkmenistan",
          "macau",
          "bahrain",
          "cambodia",
          "tajikistan"
        ],
        "category": [
          "world"
        ],
        "ai_tag": "ONLY AVAILABLE IN PROFESSIONAL AND CORPORATE PLANS",
        "sentiment": "ONLY AVAILABLE IN PROFESSIONAL AND CORPORATE PLANS",
        "sentiment_stats": "ONLY AVAILABLE IN PROFESSIONAL AND CORPORATE PLANS",
        "ai_region": "ONLY AVAILABLE IN CORPORATE PLANS",
        "ai_org": "ONLY AVAILABLE IN CORPORATE PLANS",
        "duplicate": true
      },
      {
        "article_id": "d3aba797dfa32862ad6c9b4d366dd822",
        "title": "FA charge Spurs' Bentancur over racist remark about Son",
        "link": "https://www.channelnewsasia.com/sport/fa-charge-spurs-bentancur-over-racist-remark-about-son-4604391",
        "keywords": [
          "sport"
        ],
        "creator": null,
        "video_url": null,
        "description": null,
        "content": "ONLY AVAILABLE IN PAID PLANS",
        "pubDate": "2024-09-12 14:27:48",
        "pubDateTZ": "UTC",
        "image_url": "https://onecms-res.cloudinary.com/image/upload/s--4LXOZw9d--/c_fill,h_900,w_1600/fl_relative,g_south_east,l_mediacorp:cna:watermark:2024-04:reuters_1,w_0.1/f_auto,q_auto/v1/one-cms/core/2024-09-12t142748z_1_lynxmpek8b0lu_rtroptp_3_soccer-england-tot.jpg?itok=bymrtw1e",
        "source_id": "channelnewsasia",
        "source_priority": 37829,
        "source_name": "Cna",
        "source_url": "https://www.channelnewsasia.com",
        "source_icon": "https://i.bytvi.com/domain_icons/channelnewsasia.jpg",
        "language": "english",
        "country": [
          "singapore",
          "georgia",
          "yemen",
          "afghanistan",
          "cyprus",
          "india",
          "saudi arabia",
          "maldives",
          "japan",
          "united arab emirates",
          "malaysia",
          "china",
          "south korea",
          "north korea",
          "taiwan",
          "thailand",
          "pakistan",
          "mongolia",
          "brunei",
          "lebanon",
          "indonesia",
          "kyrgyzstan",
          "syria",
          "israel",
          "bhutan",
          "iran",
          "turkey",
          "armenia",
          "qatar",
          "philippines",
          "hong kong",
          "kazakhstan",
          "iraq",
          "bangladesh",
          "laos",
          "vietnam",
          "timor-leste",
          "kuwait",
          "myanmar",
          "azerbaijan",
          "jordan",
          "nepal",
          "oman",
          "sri lanka",
          "uzbekistan",
          "turkmenistan",
          "macau",
          "bahrain",
          "cambodia",
          "tajikistan"
        ],
        "category": [
          "sports"
        ],
        "ai_tag": "ONLY AVAILABLE IN PROFESSIONAL AND CORPORATE PLANS",
        "sentiment": "ONLY AVAILABLE IN PROFESSIONAL AND CORPORATE PLANS",
        "sentiment_stats": "ONLY AVAILABLE IN PROFESSIONAL AND CORPORATE PLANS",
        "ai_region": "ONLY AVAILABLE IN CORPORATE PLANS",
        "ai_org": "ONLY AVAILABLE IN CORPORATE PLANS",
        "duplicate": false
      },
      {
        "article_id": "e2f8a9d00069ed55adb74b815b936bc4",
        "title": "Saints boss Martin not worried by criticism after losing first three games",
        "link": "https://www.channelnewsasia.com/sport/saints-boss-martin-not-worried-criticism-after-losing-first-three-games-4604381",
        "keywords": [
          "sport"
        ],
        "creator": null,
        "video_url": null,
        "description": null,
        "content": "ONLY AVAILABLE IN PAID PLANS",
        "pubDate": "2024-09-12 14:23:00",
        "pubDateTZ": "UTC",
        "image_url": "https://onecms-res.cloudinary.com/image/upload/s--p6R07cRk--/c_fill,h_900,w_1600/fl_relative,g_south_east,l_mediacorp:cna:watermark:2024-04:reuters_1,w_0.1/f_auto,q_auto/v1/one-cms/core/2024-09-12t142300z_1_lynxmpek8b0ln_rtroptp_3_soccer-england-bre-sou-report.jpg?itok=DGGdC_D1",
        "source_id": "channelnewsasia",
        "source_priority": 37829,
        "source_name": "Cna",
        "source_url": "https://www.channelnewsasia.com",
        "source_icon": "https://i.bytvi.com/domain_icons/channelnewsasia.jpg",
        "language": "english",
        "country": [
          "georgia",
          "yemen",
          "afghanistan",
          "cyprus",
          "india",
          "singapore",
          "saudi arabia",
          "maldives",
          "japan",
          "united arab emirates",
          "malaysia",
          "china",
          "south korea",
          "north korea",
          "taiwan",
          "thailand",
          "pakistan",
          "mongolia",
          "brunei",
          "lebanon",
          "indonesia",
          "kyrgyzstan",
          "syria",
          "israel",
          "bhutan",
          "iran",
          "turkey",
          "armenia",
          "qatar",
          "philippines",
          "hong kong",
          "kazakhstan",
          "iraq",
          "bangladesh",
          "laos",
          "vietnam",
          "timor-leste",
          "kuwait",
          "myanmar",
          "azerbaijan",
          "jordan",
          "nepal",
          "sri lanka",
          "uzbekistan",
          "turkmenistan",
          "macau",
          "bahrain",
          "cambodia",
          "tajikistan",
          "oman"
        ],
        "category": [
          "top"
        ],
        "ai_tag": "ONLY AVAILABLE IN PROFESSIONAL AND CORPORATE PLANS",
        "sentiment": "ONLY AVAILABLE IN PROFESSIONAL AND CORPORATE PLANS",
        "sentiment_stats": "ONLY AVAILABLE IN PROFESSIONAL AND CORPORATE PLANS",
        "ai_region": "ONLY AVAILABLE IN CORPORATE PLANS",
        "ai_org": "ONLY AVAILABLE IN CORPORATE PLANS",
        "duplicate": false
      },
      {
        "article_id": "7a792b4d87c9f42e36868c77a1b1e856",
        "title": "หุ้น Signet Jewelers พุ่งขึ้น 17% หลังจากผลประกอบการไตรมาสที่ 2 สูงกว่า",
        "link": "https://th.investing.com/news/stock-market-news/article-93CH-224506",
        "keywords": null,
        "creator": [
          "Investing.com"
        ],
        "video_url": null,
        "description": null,
        "content": "ONLY AVAILABLE IN PAID PLANS",
        "pubDate": "2024-09-12 14:22:38",
        "pubDateTZ": "UTC",
        "image_url": "https://i-invdn-com.investing.com/news/LYNXMPEA601E0_M.jpg",
        "source_id": "investing_th",
        "source_priority": 1143,
        "source_name": "Investing",
        "source_url": "https://th.investing.com",
        "source_icon": "https://i.bytvi.com/domain_icons/investing_th.png",
        "language": "thai",
        "country": [
          "thailand"
        ],
        "category": [
          "business"
        ],
        "ai_tag": "ONLY AVAILABLE IN PROFESSIONAL AND CORPORATE PLANS",
        "sentiment": "ONLY AVAILABLE IN PROFESSIONAL AND CORPORATE PLANS",
        "sentiment_stats": "ONLY AVAILABLE IN PROFESSIONAL AND CORPORATE PLANS",
        "ai_region": "ONLY AVAILABLE IN CORPORATE PLANS",
        "ai_org": "ONLY AVAILABLE IN CORPORATE PLANS",
        "duplicate": false
      }
    ],
    onlythai:function(){
      return this.data.filter(function(element,index){
          return element.language ==='thai'
      })
    },
    onlyengils:function(){
      return this.data.filter(function(element,index){
          return element.language=== 'english'
      })
    },
     onlythaipbs:function(){
      return this.data.filter(function(element,index){
          return element.source_id=== 'thaipbs'
      })
  },
  }
  console.log(news.onlythaipbs())
  
  